runtime: nodejs18

env_variables:
  SQL_USER: adminrental
  SQL_PASSWORD: "Gajahmada12"
  SQL_DATABASE: rental
  INSTANCE_CONNECTION_NAME: rental-393914:asia-northeast1:rental-database
  DATABASE_URL: mysql://adminrental:Gajahmada12@34.85.2.27/rental?socket=/cloudsql/rental-393914:asia-northeast1:rental-database
  SECRET: "RgxrEsfr4LFjATMqy8lFqNQPApL9Tu5H"
  ID_ENC: "iertjskdsmfnsf"
  CLOUDINARY_NAME: "dwkxhn2jg"
  CLOUDINARY_API_KEY: "439416349257574"
  CLOUDINARY_API_SECRET: "W1gl0QNpzCapT6pNfoENlxeBVbQ"
  CLOUDINARY_URL: "cloudinary://439416349257574:W1gl0QNpzCapT6pNfoENlxeBVbQ@dwkxhn2jg"
